const phrases: string[] = [
    "Existem duas maneiras de ser feliz nesta vida, uma é fazer-se de idiota e a outra sê-lo. -  Sigmund Freud",
    "Há momentos em que a maior sabedoria é parecer não saber nada. -  Sun Tzu",
    "A raiva é danosa para todo mundo, porém ela é mais danosa ainda para o homem que a sente. -  Epícuro",
    "Quem mais demora a fazer uma promessa é quem a cumpre mais rigorosamente. -  Jean-Jacques Rousseau",
    "Basta lembrar que, às vezes, a forma como você pensa sobre as pessoas não é a maneira como elas realmente são. -  Cidades de Papel, John Green",
    "Uma coisa é certa: ficar sentado se sentindo infeliz não vai mudar nada. -  O Menino do Pijama Listrado",
    "Muitas vezes aquilo que você pensa que vai te destruir, vem, e te fortalece e te deixa ainda melhor.",
    "Quanto maior o ego, maior a insegurança da pessoa. Gente bem resolvida é humilde, sabe que não precisa provar nada pra ninguém. E não precisa de holofotes artificiais, porque já brilha naturalmente.",
    "Queremos ter certezas e não dúvidas, resultados e não experiências, mas nem mesmo percebemos que as certezas só podem surgir através das dúvidas e os resultados somente através das experiências. -  Carl Jung",
    "O mundo está cheio de coisas óbvias que ninguém jamais observa. -  Sherlock Holmes",
    "Para ser feliz, você não precisa de grandes conquistas materiais. Você já tem o pôr-do-sol, as estrelas, os pássaros, o sorriso dos seus amigos, seus irmãos. Agradeça a Deus, pois você tem tua vida. Tem o dia que está começando, tem sua força e determinação. Com todos esses presentes da vida, o resto você constrói! -  Roberto Shinyashiki",
    "Eu não seria digna de mim se eu não estivesse atraindo alguma controvérsia e críticas. No mundo todo aquele que fez alguma coisa na vida tem sido criticado. -  Margaret Thatcher",
    "O mais corajoso dos atos ainda é pensar com a própria cabeça. -  Coco Chanel",
    "Há quem fique contigo quando sobra tempo… Há quem arranje tempo pra ficar contigo… Aprenda a diferença",
    "Você pode saber o que disse, mas nunca o que outro escutou. -  Jacques Lacan",
    "A maioria das pessoas não quer realmente a liberdade, pois liberdade envolve responsabilidade, e a maioria das pessoas tem medo de responsabilidade. -  Sigmund Freud",
    "Toda forma de vício é ruim, não importa que seja droga, álcool ou idealismo. -  Carl Jung",
    "A esperança tem duas filhas lindas, a indignação e a coragem; a indignação nos ensina a não aceitar as coisas como estão; a coragem, a mudá-las. -  Santo Agostinho",
    "Só os covardes vão embora quando as coisas ficam difíceis. -  Estação onze",
    "Aquele que não prevê as coisas longínquas expõe-se a desgraças próximas. -  Confúcio",
    "Não encontro defeitos. Encontro soluções. Qualquer um sabe se queixar. -  Henry Ford",
    "É loucura odiar todas as rosas porque uma te espetou. Entregar todos os teus sonhos porque um deles não se realizou, perder a fé em todas as orações porque em uma não foi atendido, desistir de todos os esforços porque um deles fracassou. É loucura condenar todas as amizades porque uma te traiu, descrer de todo amor porque um deles te foi infiel. É loucura jogar fora todas as chances de ser feliz porque uma tentativa não deu certo. Espero que na tua caminhada não cometas estas loucuras. Lembrando que sempre há uma outra chance, uma outra amizade, um outro amor, uma nova força. Para todo fim, um recomeço. -  Saint-Exupéry",
    "Quando não há inimigos interiores, os inimigos exteriores não conseguem te ferir. -  Provérbio Africano",
    "Uma das trágicas coisas que eu percebo na natureza humana é que todos nós tendemos a adiar o viver. Estamos todos sonhando com um mágico jardim de rosas no horizonte, ao invés de desfrutar das rosas que estão florescendo do lado de fora de nossas janelas hoje. -  Dale Carnegie",
    "Nossa casa é um dos melhores lugares do mundo para se ficar. Tem gente que acha deprimente ficar em casa nos finais de semana. Deprimente é não ter lar, não ter raízes! Sair só é bom quando sabemos que temos para onde voltar. -  André Mansur",
    "Todo trabalho que me foi negado … abriu a porta para novas oportunidades. Todos relacionamentos que me machucaram … me levaram para o meu verdadeiro amor. Cada erro que eu pensei que seria o fim de mim … me apontou para um sucesso incrível. Às vezes, quando você acha que está perdendo, você está ganhando. -  Steve Maraboli",
    "Não nos deixemos perturbar por ninharias, que devemos desprezar e esquecer. Lembre-se ” A vida é muito curta para sermos mesquinhos”. -  Dale Carnegie",
    "Seja uma boa pessoa mas não perca seu tempo provando isso.",
    "As pessoas perfeitas não mentem, não bebem, não brigam, não discutem, não erram e não existem.",
    "Ser humilde não é acreditar que somos menos que os outros. É saber que não somos mais que ninguém. -  Carlos Hilsdorf",
    "Culpas, desculpas e culpados são pesos desnecessários que travam os passos, corroem os laços e impedem o caminhar. Assuma a responsabilidade que lhe cabe, repare o que for possível e avance sem olhar pra trás.",
    "As vezes não é a DOR que faz você sofrer, são os seus pensamentos negativos que fazem as coisas parecerem piores que realmente são.",
    "Eu estou deixando falarem, acharem, especularem e pensarem. se tem algo que a vida me ensinou é que nunca vou contentar todo mundo. Mas se eu conseguir estar em paz comigo mesma, já é suficiente.",
    "Tempo é uma coisa, inteligência outra. Cabelo branco não é sinônimo de vida inteligente. -  Iaponira Barros",
    "Tentar ser feliz acumulando bens materiais é como satisfazer a fome colocando sanduíches em volta do corpo. -  George Carlin",
    "A inveja a raiva e os insultos, quando não aceitos continuam pertencendo a quem os carregava consigo. -  Provérbio Zen",
    "Não vemos as coisas como são. Vemos as coisas como somos.",
    "Se quiséssemos ser apenas felizes, isso não seria difícil. Mas como queremos ficar mais felizes do que os outros, é difícil, porque achamos os outros mais felizes do que realmente são. -  Montesquieu",
    "Tem pessoas que nunca desistem apesar de tudo, acho que é assim que nascem os heróis. Heróis não precisam ter capas, máscaras e super poderes. Precisam ser corajosos, ser duros com os problemas e ter coração forte. A gente é herói quando jamais desiste.",
    "Tem gente que esquece que você não precisa diminuir o outro para crescer – Uma pessoa humilde é aquela que não diminui o outro para crescer, há pessoas que são tão arrogantes que elas só conseguem se elevar se ela diminuir a outra pessoa, e há pessoas inteligentes que crescem junto com o outro. -  Mario Sergio Cortella",
    "Saber lidar com a derrota não é ser fraco, é ser humilde.",
    "O segredo da saúde mental e corporal está em não se lamentar pelo passado, não se preocupar com o futuro, nem se adiantar aos problemas, mas viver sabia e seriamente o presente. -  Buda",
    "A tragédia começa quando os dois acham que tem razão. -  William Shakespeare",
    "Na vida, diante das adversidades, a gente tem sempre duas escolhas; se conformar ou enfrentar. Se você acha que não vale a luta, então saiba que está abrindo mão da conquista. -  Bendita Cuca",
    "O forte chora , o forte sente dor, o forte sofre, o forte esmorece , o forte chega até a desfalecer na fé, mas o bonito de tudo é que o forte não desiste… -  Cecilia Sfalsin",
    "A disciplina é a vitória da razão sobre a preguiça. -  Flavio Gikovate",
    "Por mais inteligente que alguém possa ser, se não for humilde, o seu melhor se perde na arrogância. A humildade ainda é a parte mais bela da sabedoria.",
    "Não destrua o futuro com problemas do passado. -   ",
    "Sofremos demais pelo pouco que não temos, alegramo-nos pouco com o muito que possuímos. -  William Shakespeare",
    "O problema não é tropeçar. Mas apegar-se à pedra.",
    "A sua vida só vai pra frente depois que você se desapega das pessoas que te levam pra trás.",
    "As nuvens sempre passam. Podem ser nuvens claras ou escuras, mas sempre passam. Talvez tenha que chover uma tempestade, mas ela também passa. Compreenda que você não é a nuvem, você é o céu.",
    "Você realmente descobre a sua força quando superar não é uma opção, e sim uma necessidade!",
    "Quando não compreendemos a dor ela nos dilacera. Quando entendemos seus fins, ela nos aperfeiçoa. -  Provérbio Chinês",
    "Atitude é uma coisa pequena que faz toda a diferença.",
    "Uma pessoa é única ao estender a mão, e ao recolhê-la inesperadamente torna-se mais uma. O egoísmo unifica os insignificantes. -  William Shakespeare",
    "Sonhe, acredite, pense, lute, levante-se e aja. Apenas não desista. A vitória requer suor e esforço. A única coisa que não requer esforço, é a ilusão. E nesse mundo, estão todos fartos de se iludir.",
    "Se você já superou ausências, saudades, tristezas, o tempo e algumas feridas, então não duvide de si mesmo. Você pode lidar com qualquer coisa.",
    "Sobre todas as coisas, para que alguém se torne digno de confiança, tão certo quanto a noite sucede o dia, é preciso nunca ser falso consigo mesmo. -  William Shakespeare",
    "Nenhuma queda é em vão, nenhuma dor o consome sem lhe ensinar algo; aceite as circunstâncias. Nada em sua vida acontece em vão, aceite a lição. Por trás de cada adversidade encontra-se um fragmento para a sua evolução. -  Vinicius N. Morais",
    "É muito melhor perceber um defeito em si mesmo, do que dezenas no outro, pois o seu defeito você pode mudar. -  Dalai Lama",
    "Nesta vida temos três professores importantes: o Momento Feliz, o Momento Triste e o Momento Difícil. O Momento Feliz mostra o que não precisamos mudar. O Momento Triste mostra o que precisamos mudar. O Momento Difícil mostra que somos capazes de superar. -  Roberto Shinyashiki",
    "A vida não é triste. Tem horas tristes. -  Romain Rolland",
    "Se você está atravessando um inferno, bem, continue atravessando. -  Winston Churchill",
    "Em nossas vidas, a mudança é inevitável. A perda é inevitável. A felicidade reside na nossa adaptabilidade em sobreviver a tudo de ruim.",
    "Humildade não é pensar menos DE si mesmo, humildade é pensar menos EM si mesmo. -  C.S. Lewis",
    "Ser ruim em alguma coisa é o primeiro passo para se tornar bom em alguma coisa. -  Hora da Aventura",
    "Quando algo ruim acontece você tem três escolhas: deixar isso definir você, deixar isso destruir você ou fazer isso te deixar mais forte.",
    "Se você não encontrar uma solução, crie uma.",
    "Ser humilde não é acreditar que somos menos que os outros. É saber que não somos mais que ninguém. -  Carlos Hilsdorf",
    "O período de maior ganho em conhecimento e experiência é o período mais difícil da vida de alguém. -  Dalai Lama",
    "O melhor caminho para se sair de uma dificuldade é através dela.",
    "Divide as dificuldades que encontras em tantas partes como seja possível para sua melhor solução. -  René Descartes",
    "Se você ultrapassar aquela sensação de medo. Aquele sentimento de estar correndo um risco. Coisas verdadeiramente maravilhosas podem acontecer.",
    "A sua estrada é somente sua. Outros podem acompanha-lo mas ninguém pode andar por você.",
    "Seja humilde para admitir seus erros, inteligente para aprender com eles e maduro para corrigi-los.",
    "É melhor ser rei de teu silêncio do que escravo de tuas palavras.",
    "Seja como for o que penses, creio que é melhor dizê-lo com boas palavras. -  William Shakespeare",
    "Quando você discute, inflama-se e se contradiz, você pode, algumas vezes, conseguir uma vitória; mas será uma vitória sem proveito, porque nunca contará com a boa vontade do seu oponente. -  Benjamin Franklin",
    "As pessoas comuns pensam apenas como passar o tempo. Uma pessoa inteligente tenta usar o tempo. -  Arthur Schopenhauer",
    "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças -  Charles Darwin",
    "Tudo aquilo que o homem ignora, não existe para ele. Por isso o universo de cada um, se resume ao tamanho do seu saber. -  Albert Einstein",
    "Para saber quais são, verdadeiramente, as opiniões de um homem, deve-se prestar a atenção, mais ao que ele pratica, do que ao que ele diz. -  Descartes",
    "Um homem nunca te diz algo até que você o contradiga. -  George Bernard Shaw",
    "O que vale na vida não é o ponto de partida e sim a caminhada. Caminhando e semeando, no fim terás o que colher. -  Cora Coralina",
    "Falhar em preparar-se é preparar-se para falhar. -  Benjamin Franklin",
    "Não permita que o comportamento dos outros tire a sua própria paz! -  Dalai Lama",
    "Você deve lutar mais de uma batalha para se tornar uma vencedora. -  Margaret Thatcher",
    "Todos os homens têm medo. Quem não tem medo não é normal; isso nada tem a ver com a coragem. -  Jean-Paul Sartre",
    "Deve-se aprender sempre, até mesmo com um inimigo. -  Isaac Newton",
    "O coração que está em paz é uma festa em todas as aldeias -  Provérbio Hindu",
    "Coragem é mais estimulante do que medo e a longo prazo é mais fácil. Nós não precisamos nos tornar heróis da noite para o dia. Apenas um passo por vez, encarando cada coisa que aparecer, percebendo que não é tão terrível quanto parecia ser, descobrindo que nós temos a força para encarar. -  Eleanor Roosevelt",
    "Eu tentei 99 vezes e falhei, mas na centésima tentativa eu consegui, nunca desista de seus objetivos mesmo que esses pareçam impossíveis, a próxima tentativa pode ser a vitoriosa. -  Albert Einsten",
    "A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original. -  Albert Einsten",
    "Uma pessoa inteligente resolve um problema, um sábio previne-­o.",
    "Feliz aquele que atravessou a vida ajudando o seu semelhante, que não conheceu o medo e se manteve alheio à agressividade e ao ressentimento! É dessa madeira que são esculpidas as figuras ideais, que consolam a Humanidade nas situações de sofrimento que ela própria criou.",
    "Sempre é hora de fazer o que é certo. -  Martin Luther King",
    "Saiba que seu destino é traçado pelos seus próprios pensamentos, e não por alguma força que venha de fora. -  Martin Luther King",
    "A palavra coragem é muito interessante. Ela vem da raiz latina cor, que significa “coração”. Por tanto, ser corajoso signirica viver com o coração. E os fracos, somente os fracos, vivem com a cabeça; receosos, eles criam em torno deles uma segurança baseada na lógica. Com cedo. fecham todas a janelas e portas – com teologia, conceitos, palavras, teorias – e do lado de dentro dessas portas e janelas, ele se escondem.",
    "Tudo bem celebrar o sucesso, mas é mais importante guardar as lições das falhas. -  Bill Gates",
    "O que não provoca minha morte faz com que eu fique mais forte. -  Friedrich Nietzsche",
    "Não ter medo é como fazer musculação. Quanto mais eu me exercito, menor a chance de meus temores me dominarem. -  Arianna Huffington",
    "Frequentemente é necessário mais coragem para ousar fazer certo do que temer fazer errado. -  Abraham Lincoln",
    "Sempre me sinto feliz, sabes por quê? Porque não espero nada de ninguém, esperar sempre dói, os problemas não são eternos, sempre têm solução, o único que não se resolve é a morte. A vida e curta, por isso, ame-a! Viva intensamente e recorde: Antes de falar, escute; Antes de escrever, pense; Antes de criticar, examine; Antes de ferir, sinta; Antes de orar, perdoe; Antes de gastar, ganhe; Antes de se render, tente de novo; Antes de morrer, viva!!",
    "O que você faz com seus problemas no final do dia? Leva-os para casa e os convida para a mesa de jantar? Ao dormir, você permite que eles se deitem na sua cama e transformem seus sonhos em pesadelos? A maneira como lidamos com nossos problemas diários tem um forte impacto sobre nossa saúde física e mental, sobre nosso desempenho profissional e, especialmente, sobre nossa vida familiar.",
    "Autoconfiança não é arrogância ou prepotência. É a certeza de que você tem plenas condições de vencer.",
    "Nós nunca descobriremos o que vem depois da escolha, se não tomarmos uma decisão. Por isso, entenda os seus medos, mas jamais deixe que eles sufoquem os seus sonhos. Siga o coelho. Não tenha medo de entrar em lugares onde você acha que não cabe. -  Bruna Vieira",
    "Imagine uma nova história para sua vida e acredite nela. -  Paulo Coelho",
    "Um momento de paciência pode evitar um grande desastre; um momento de impaciência pode arruinar toda uma vida. -  provérbios orientais",
    "Todas as flores do futuro estão nas sementes de hoje. -  provérbios orientais",
    "Um pouco de perfume sempre fica nas mãos de quem oferece flores. -  provérbios orientais",
    "A maior vingança contra um inimigo é perdoá-lo. Quando o perdoamos, ele morre dentro de nós e deixa de nos perturbar. -  Augusto Cury",
    "Você é livre para fazer suas escolhas, mas é prisioneiro das consequências. -  Pablo Neruda",
    "A mais alta forma de ignorância é quando você rejeita algo sobre o qual você não sabe nada. -  Wayne Dyer",
    "Experiência não é o que acontece com a gente, mas o que fazemos com o que nos acontece.",
    "O silêncio é um amigo que nunca trai. - provérbios orientais",
    "Há três coisas que nunca voltam atrás: a flecha lançada, a palavra pronunciada e a oportunidade perdida. - provérbios orientais",
    "É impossível haver progresso sem mudança. Quem não muda a si mesmo não muda coisa alguma. - Bernard Shaw",
];
export function randomText() {
    return phrases[Math.floor(Math.random() * phrases.length)];
}